name: IRCv3 Working Group
markdown: kramdown
highlighter: pygments
# baseurl: http://ircv3.org
exclude:
  - README.md
gems:
  - jekyll-sitemap
sitemap:
  file: "/sitemap.xml"
collections:
  irc:
    output: true
